version: "2.1"

services:
    sql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=12345 --execute \"SHOW DATABASES\""
            interval: 5s
            timeout: 30s
            retries: 5
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: relman

    relman:
        build: ./relman
        links:
            - sql
        depends_on:
            sql:
               condition: service_healthy
        ports:
            - "8080:8443"
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://sql/relman?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: 12345

