@startuml
DOCKER_SPRING *-- JAVASCRIPT
JAVASCRIPT *-- HTML
HTML *-- DISEÑO_WEB
HTML *-- ETIQUETAS
HTML *-- VIDEOS
HTML *-- SPRING
SPRING *-- SEGURIDAD_SPRING
SPRING *-- IMAGENES
HTML *-- CSS
CSS *-- BOOTSTRAP
HTML *-- API_REST
@enduml
