@startuml
SPRING *-- SEGURIDAD_SPRING
SPRING *-- DOCKER_SPRING
DOCKER_SPRING *-- JAVASCRIPT
JAVASCRIPT *-- HTML
HTML *-- DISEÑO_WEB
HTML *-- ETIQUETAS
HTML *-- VIDEOS
HTML *-- CSS
CSS *-- BOOTSTRAP
HTML *-- API_REST
SPRING *-- IMAGENES
@enduml
