@startuml
CSS *-- HTML
HTML *-- DISEÑO_WEB
HTML *-- ETIQUETAS
HTML *-- VIDEOS
HTML *-- SPRING
SPRING *-- SEGURIDAD_SPRING
SPRING *-- DOCKER_SPRING
SPRING *-- IMAGENES
HTML *-- API_REST
CSS *-- BOOTSTRAP
@enduml
