@startuml 
 set namespaceSeparator none
SGML <|-- HTML
MAQUETACIÓN_WEB <|-- HTML
COMP1 *-- HTML
COMP2 *-- HTML
USAN1 <-- HTML
USAN2 <-- HTML
ASOCIADOS1 <-- HTML
ASOCIADOS2 <-- HTML
HTML <|-- HTML2.1
HTML <|-- HTML4.0
HTML *-- PARTES1
HTML *-- PARTES2
HTML <-- USA1
HTML <-- USA2
HTML <-- ASOCIADO1
HTML <-- ASOCIADO2
@enduml
