@startuml 
 set namespaceSeparator none
SGML <|-- HTML
MAQUETACIÓN_WEB <|-- HTML
HTML4.0 <|-- HTML
CSS *-- HTML
ETIQUETAS *-- HTML
ATRIBUTOS *-- HTML
JAVASCRIPT <-- HTML
ANGULAR <-- HTML
CSS -- HTML
XML -- HTML
HTML <|-- HTML2.1
HTML <|-- HTML4.0
HTML *-- DISEÑO_WEB
HTML *-- ETIQUETAS
HTML *-- VIDEOS
HTML *-- ANGULAR
HTML <-- CSS
HTML <-- XML
HTML -- CSS
HTML -- XML
@enduml
