@startuml 
 set namespaceSeparator none
SGML <|-- HTML
MAQUETACIÓN_WEB <|-- HTML
HTML4.0 <|-- HTML
XML <|-- HTML
JAVASCRIPT <|-- HTML
ATRIBUTOS <|-- HTML
JAVASCRIPT <|-- HTML
CSS <|-- HTML
CSS *-- HTML
ETIQUETAS *-- HTML
ATRIBUTOS *-- HTML
HTML4.0 *-- HTML
JAVASCRIPT *-- HTML
SGML *-- HTML
JAVASCRIPT <-- HTML
ANGULAR <-- HTML
ANGULAR <-- HTML
CSS -- HTML
XML -- HTML
DOCKER_SPRING -- HTML
VIDEOS -- HTML
HTML4.0 -- HTML
HTML <|-- HTML2.1
HTML <|-- HTML4.0
HTML <|-- BOOTSTRAP
HTML *-- DISEÑO_WEB
HTML *-- ETIQUETAS
HTML *-- VIDEOS
HTML *-- SPRING
HTML *-- CSS
HTML *-- API_REST
HTML <-- CSS
HTML <-- XML
HTML <-- MAQUETACIÓN_WEB
HTML -- CSS
HTML -- XML
HTML -- MAQUETACIÓN_WEB
HTML -- ETIQUETAS
HTML -- IMAGENES
@enduml
